transmister/main/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "main"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path(
        "user-transcriptions/",
        views.UserTranscriptionsView.as_view(),
        name="user-transcriptions",
    ),
    path("upload/", views.upload_audio, name="upload"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transmister/transmister/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
]

transmister/main/models.py
import uuid
from datetime import datetime
from django.db import models
from django.urls.base import reverse


def recording_path(instance, filename):
    return f"recordings/{instance.session}/{instance.pk}.wav"


class Recording(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    session = models.IntegerField()
    voice_recording = models.FileField(upload_to=recording_path)
    language = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        verbose_name = "Record"
        verbose_name_plural = "Records"

    def __str__(self):
        return str(self.id)

    def get_absolute_url(self):
        return reverse("main:record_detail", kwargs={"id": str(self.id)})


class Transcription(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    created = models.DateTimeField(auto_now_add=True)
    session = models.IntegerField()
    file = models.FileField()
    language = models.CharField(max_length=50, null=True, blank=True)

    class Meta:
        verbose_name = "Transcription"
        verbose_name_plural = "Transcriptions"

    def __str__(self):
        return str(self.id)

    def get_file_name(self):
        return self.file.name.split("/")[-1]

    def get_content(self):
        with open(self.file.name, "r") as f:
            content = f.readlines()
        return content

transmister/main/views.py
import os
import glob
from datetime import datetime
from typing import Any, Dict
from django.views.generic import TemplateView
from django.views import View
from django.contrib import messages
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, render, redirect

from transmister.settings import MEDIA_ROOT, MEDIA_URL
from .models import Recording, Transcription
from .utils import transcribe, logger


class HomeView(TemplateView):
    """Home page"""

    template_name = "main/recording.html"

    def get(self, request):
        context = {}
        try:
            session_id = request.session["session"]
            session_path = f"{MEDIA_ROOT}/recordings/{request.session['session']}"
            if glob.glob(f"{session_path}/transcript_{session_id}.txt"):
                with open(
                    f"{session_path}/transcript_{session_id}.txt", "r"
                ) as txt_file:
                    context["transcription"] = txt_file.read()
        except:
            logger.warning("no session ID exising. segging a new one")

        # Setting a new session ID (timestamp) for the files path
        request.session["session"] = int(datetime.timestamp(datetime.now()))
        return render(request, self.template_name, context=context)

    def post(self, request):
        session_id = request.session["session"]
        session_path = f"{MEDIA_ROOT}/recordings/{session_id}"
        files = sorted(glob.glob(f"{session_path}/*.wav"), key=os.path.getmtime)
        if len(files) > 0:
            transcription_file = f"{session_path}/transcript_{session_id}.txt"
            with open(transcription_file, "a") as txt_file:
                for idx, file in enumerate(files, start=1):
                    txt = transcribe(file)
                    txt_file.writelines(f"{idx}- {txt}\n")
            Transcription.objects.create(file=transcription_file, session=session_id)

        else:
            messages.warning(request, "No files to transcribe")
        return redirect(request.META["HTTP_REFERER"])


class UserTranscriptionsView(TemplateView):
    """List of all current recordings that the user has"""

    template_name = "main/user_transcriptions.html"

    def get_context_data(self, **kwargs: Any) -> Dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context["media_url"] = f"{MEDIA_URL}recordings"
        context["transcs"] = Transcription.objects.all()
        return context


def upload_audio(request):
    try:
        audio_blob = request.FILES["audio_blob"]
        Recording.objects.create(
            session=request.session["session"], voice_recording=audio_blob
        )
        return JsonResponse({"success": True})
    except Exception as e:
        print(e)
        return JsonResponse({"success": False})

transmister/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <!-- Meta, title, CSS, favicons, etc. -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Transmister | Transcriber Tool</title>
  <title>{% block title %}{% endblock %}</title>
  <!-- Bootstrap -->
  <link href="{% static 'vendors/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
  <!-- Font Awesome -->
  <link href="{% static 'vendors/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
  <!-- NProgress -->
  <link href="{% static 'vendors/nprogress/nprogress.css' %}" rel="stylesheet">
  <!-- jQuery custom content scroller -->
  <link href="{% static 'vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.min.css' %}" rel="stylesheet" />

  <!-- Custom Theme Style -->
  <link href="{% static 'build/css/custom.min.css' %}" rel="stylesheet">
</head>

<body class="nav-md">
  <div class="container body">
    <div class="main_container">
      <!-- Sidebar  -->
      {% include 'main/includes/_sidebar.html' %}
      <!-- End sidebar -->

      <!-- top navigation -->
      {% include 'main/includes/_top_navbar.html' %}
      <!-- /top navigation -->

      <!-- page content -->
      <div class="right_col" role="main">
        <div class="">
          <div class="page-title">
            {% block content %}
            {% endblock content %}
          </div>
        </div>
      </div>
      <!-- /page content -->

      <!-- footer content -->
      <footer>
        <div class="pull-right">
          Transmister <a href="https://actappon.com">by Actappon</a>
        </div>
        <div class="clearfix"></div>
      </footer>
      <!-- /footer content -->
    </div>
  </div>

  {% block js %}
  {% endblock js %}
  <!-- jQuery -->
  <script src="{% static 'vendors/jquery/dist/jquery.min.js' %}"></script>
  <!-- Bootstrap -->
  <script src="{% static 'vendors/bootstrap/dist/js/bootstrap.min.js' %}"></script>
  <!-- FastClick -->
  <script src="{% static 'vendors/fastclick/lib/fastclick.js' %}"></script>
  <!-- NProgress -->
  <script src="{% static 'vendors/nprogress/nprogress.js' %}"></script>
  <!-- jQuery custom content scroller -->
  <script src="{% static 'vendors/malihu-custom-scrollbar-plugin/jquery.mCustomScrollbar.concat.min.js' %}"></script>

  <!-- Custom Theme Scripts -->
  <script src="{% static 'build/js/custom.min.js' %}"></script>
</body>

</html>

transmister/main/templates/main/includes/_sidebar.html
<div class="col-md-3 left_col menu_fixed">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>TransMister!</span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                <img src="images/img.jpg" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2>John Doe</h2>
            </div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <ul class="nav side-menu">
                    <li><a href="{% url 'main:home' %}"><i class="fa fa-home"></i> Home </a></li>
                    <li><a href="{% url 'main:user-transcriptions' %}"><i class="fa fa-edit"></i> My Transcriptions</a>
                    </li>
                </ul>
                <h3>General</h3>
                <ul class="nav side-menu">
                    <li><a href="https://colorlib.com/polygon/gentelella/fixed_footer.html" target="_blank">
                            <i class="fa fa-gear"></i> Theme reference </a></li>
                </ul>
            </div>
        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
        </div>
        <!-- /menu footer buttons -->
    </div>
</div>

transmister/main/templates/main/includes/_sidebar_original.html
<div class="col-md-3 left_col menu_fixed">
    <div class="left_col scroll-view">
        <div class="navbar nav_title" style="border: 0;">
            <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Gentelella Alela!</span></a>
        </div>

        <div class="clearfix"></div>

        <!-- menu profile quick info -->
        <div class="profile clearfix">
            <div class="profile_pic">
                <img src="images/img.jpg" alt="..." class="img-circle profile_img">
            </div>
            <div class="profile_info">
                <span>Welcome,</span>
                <h2>John Doe</h2>
            </div>
        </div>
        <!-- /menu profile quick info -->

        <br />

        <!-- sidebar menu -->
        <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
            <div class="menu_section">
                <h3>General</h3>
                <ul class="nav side-menu">
                    <li><a><i class="fa fa-home"></i> Home <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="index.html">Dashboard</a></li>
                            <li><a href="index2.html">Dashboard2</a></li>
                            <li><a href="index3.html">Dashboard3</a></li>
                        </ul>
                    </li>
                    <li><a><i class="fa fa-edit"></i> Forms <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="form.html">General Form</a></li>
                            <li><a href="form_advanced.html">Advanced Components</a></li>
                            <li><a href="form_validation.html">Form Validation</a></li>
                            <li><a href="form_wizards.html">Form Wizard</a></li>
                            <li><a href="form_upload.html">Form Upload</a></li>
                            <li><a href="form_buttons.html">Form Buttons</a></li>
                        </ul>
                    </li>
                    <li><a><i class="fa fa-desktop"></i> UI Elements <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="general_elements.html">General Elements</a></li>
                            <li><a href="media_gallery.html">Media Gallery</a></li>
                            <li><a href="typography.html">Typography</a></li>
                            <li><a href="icons.html">Icons</a></li>
                            <li><a href="glyphicons.html">Glyphicons</a></li>
                            <li><a href="widgets.html">Widgets</a></li>
                            <li><a href="invoice.html">Invoice</a></li>
                            <li><a href="inbox.html">Inbox</a></li>
                            <li><a href="calendar.html">Calendar</a></li>
                        </ul>
                    </li>
                    <li><a><i class="fa fa-table"></i> Tables <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="tables.html">Tables</a></li>
                            <li><a href="tables_dynamic.html">Table Dynamic</a></li>
                        </ul>
                    </li>
                    <li><a><i class="fa fa-bar-chart-o"></i> Data Presentation <span
                                class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="chartjs.html">Chart JS</a></li>
                            <li><a href="chartjs2.html">Chart JS2</a></li>
                            <li><a href="morisjs.html">Moris JS</a></li>
                            <li><a href="echarts.html">ECharts</a></li>
                            <li><a href="other_charts.html">Other Charts</a></li>
                        </ul>
                    </li>
                    <li><a><i class="fa fa-clone"></i>Layouts <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="fixed_sidebar.html">Fixed Sidebar</a></li>
                            <li><a href="fixed_footer.html">Fixed Footer</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
            <div class="menu_section">
                <h3>Live On</h3>
                <ul class="nav side-menu">
                    <li><a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="e_commerce.html">E-commerce</a></li>
                            <li><a href="projects.html">Projects</a></li>
                            <li><a href="project_detail.html">Project Detail</a></li>
                            <li><a href="contacts.html">Contacts</a></li>
                            <li><a href="profile.html">Profile</a></li>
                        </ul>
                    </li>
                    <li><a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="page_403.html">403 Error</a></li>
                            <li><a href="page_404.html">404 Error</a></li>
                            <li><a href="page_500.html">500 Error</a></li>
                            <li><a href="plain_page.html">Plain Page</a></li>
                            <li><a href="login.html">Login Page</a></li>
                            <li><a href="pricing_tables.html">Pricing Tables</a></li>
                        </ul>
                    </li>
                    <li><a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
                        <ul class="nav child_menu">
                            <li><a href="#level1_1">Level One</a>
                            <li><a>Level One<span class="fa fa-chevron-down"></span></a>
                                <ul class="nav child_menu">
                                    <li class="sub_menu"><a href="level2.html">Level Two</a>
                                    </li>
                                    <li><a href="#level2_1">Level Two</a>
                                    </li>
                                    <li><a href="#level2_2">Level Two</a>
                                    </li>
                                </ul>
                            </li>
                            <li><a href="#level1_2">Level One</a>
                            </li>
                        </ul>
                    </li>
                    <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span
                                class="label label-success pull-right">Coming Soon</span></a></li>
                </ul>
            </div>

        </div>
        <!-- /sidebar menu -->

        <!-- /menu footer buttons -->
        <div class="sidebar-footer hidden-small">
            <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
            </a>
            <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
            </a>
        </div>
        <!-- /menu footer buttons -->
    </div>
</div>

transmister/main/templates/main/includes/_top_navbar.html
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown"
                        aria-expanded="false">
                        <img src="images/img.jpg" alt="">John Doe
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="javascript:;"> Profile</a></li>
                        <li>
                            <a href="javascript:;">
                                <span class="badge bg-red pull-right">50%</span>
                                <span>Settings</span>
                            </a>
                        </li>
                        <li><a href="javascript:;">Help</a></li>
                        <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                    </ul>
                </li>

                <li role="presentation" class="dropdown">
                    <a href="javascript:;" class="dropdown-toggle info-number" data-toggle="dropdown"
                        aria-expanded="false">
                        <i class="fa fa-envelope-o"></i>
                        <span class="badge bg-green">6</span>
                    </a>
                    <ul id="menu1" class="dropdown-menu list-unstyled msg_list" role="menu">
                        <li>
                            <a>
                                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                <span>
                                    <span>John Smith</span>
                                    <span class="time">3 mins ago</span>
                                </span>
                                <span class="message">
                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                <span>
                                    <span>John Smith</span>
                                    <span class="time">3 mins ago</span>
                                </span>
                                <span class="message">
                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                <span>
                                    <span>John Smith</span>
                                    <span class="time">3 mins ago</span>
                                </span>
                                <span class="message">
                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                </span>
                            </a>
                        </li>
                        <li>
                            <a>
                                <span class="image"><img src="images/img.jpg" alt="Profile Image" /></span>
                                <span>
                                    <span>John Smith</span>
                                    <span class="time">3 mins ago</span>
                                </span>
                                <span class="message">
                                    Film festivals used to be do-or-die moments for movie makers. They were where...
                                </span>
                            </a>
                        </li>
                        <li>
                            <div class="text-center">
                                <a>
                                    <strong>See All Alerts</strong>
                                    <i class="fa fa-angle-right"></i>
                                </a>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>

transmister/main/templates/main/recording.html
{% extends 'main/base.html' %}

{% block content %}
<div class="row">
    <div class="col-sm-12 col-lg-12 col-md-12 col-12">
        <h1>Record and transcribe</h1>
    </div>
</div>
<div class="row mb-5">
    <div class="col-sm-12 col-lg-12 col-md-12 col-12">
        <button id="record-button" class="btn btn-lg btn-primary">Record</button>
        <span id="recording-time" style="margin-left: 10px;"></span>
    </div>
</div>
<ul>
    {% for rec in recordings.get_session_recordings %}
    <li>{{ rec }}</li>
    {% endfor %}
</ul>
<form action="{% url 'main:home' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="row">
        <div class="col-sm-12 col-lg-12 col-md-12 col-12">
            <button class="btn btn-lg w-100 btn-warning" type="submit" name="transcribe">Transacribe</button>
        </div>
    </div>
</form>

<div class="row w-100">
    <div class="col-12">
        <div class="x_panel">
            <div class="x_title">
                <h2>Audio text</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="bs-example" data-example-id="simple-jumbotron">
                    <div class="jumbotron">
                        {{ transcription }}
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-lg-12 col-md-12 col-12">
        <button class="btn btn-danger" onclick="location.reload();">Clear</button>
    </div>
</div>
{% endblock %}

{% block js %}
<script>
    var recording = false;
    var mediaRecorder;
    var chunks = [];
    var timer = null;
    var recordingTime = 0;

    function startRecording() {
        console.log(`START...`);

        navigator.mediaDevices.getUserMedia({ audio: true })
            .then(function (stream) {
                mediaRecorder = new MediaRecorder(stream);
                mediaRecorder.addEventListener("dataavailable", function (event) {
                    chunks.push(event.data);
                });
                mediaRecorder.addEventListener("stop", function () {
                    var blob = new Blob(chunks, { type: "audio/wav" });
                    clearInterval(timer);
                    recordingTime = 0;
                    var formData = new FormData();
                    formData.append("audio_blob", blob, "recording.wav");
                    formData.append("csrfmiddlewaretoken", '{{ csrf_token }}')
                    $.ajax({
                        url: "{% url 'main:upload' %}",
                        type: "POST",
                        data: formData,
                        processData: false,
                        contentType: false,
                        success: function () {
                            chunks = [];
                        }
                    });
                });
                mediaRecorder.start();
                recording = true;
                startTimer();
            });
    }

    function stopRecording() {
        console.log(`STOP!`);
        mediaRecorder.stop();
        clearInterval(timer);
        recordingTime = 0;
        recording = false;
    }

    function startTimer() {
        timer = setInterval(function () {
            recordingTime++;
            document.getElementById("recording-time").innerText = "Recording time: " + recordingTime + " seconds";
        }, 1000);
    }

    document.getElementById("record-button").addEventListener("click", function () {
        if (recording) {
            stopRecording();
            document.getElementById("record-button").innerText = "Record";
            document.getElementById("recording-time").innerText = "";
        } else {
            console.log(`starting record...`);
            startRecording();
            document.getElementById("record-button").innerText = "Stop";
        }
    });
</script>
{% endblock js %}

transmister/main/templates/main/user_transcriptions.html
{% extends 'main/base.html' %}
{% load static %}
{% load social_share %}
{% block content %}
<div class="row">
    <div class="col-sm-12">
        <h1>My Transcriptions</h1>
    </div>
</div>
<style>
    li {
        font-size: 2rem;
    }

    .limit {
        max-width: 100%;
        word-wrap: break-word;
    }
</style>
<div class="x_panel">
    <div class="x_title">
        <h2><i class="fa fa-align-left"></i> </h2>
        <div class="clearfix"></div>
    </div>
    <div class="x_content">
        <!-- start accordion -->
        <div class="accordion" id="accordion" role="tablist" aria-multiselectable="true">
            {% for trans in transcs %}
            <div class="panel">
                <a class="panel-heading" role="tab" id="heading_{{ forloop.counter }}" data-toggle="collapse"
                    data-parent="#accordion" href="#collapse_{{ forloop.counter }}" aria-expanded="false"
                    aria-controls="collapse_{{ forloop.counter }}">
                    <h4 class="panel-title">{{ trans.get_file_name }}</h4>
                </a>
                <div id="collapse_{{ forloop.counter }}" class="panel-collapse collapse" role="tabpanel"
                    aria-labelledby="heading_{{ forloop.counter }}">
                    <div class="panel-body">
                        <p class="limit">
                            {% for line in trans.get_content %}
                            {{ line }}
                            <br>
                            {% endfor %}
                        </p>
                    </div>
                    <div class="panel-footer">
                        <a href="{{ media_url }}/{{ trans.session }}/{{ trans.get_file_name }}"
                            download="{{ trans.get_file_name }}" class="btn btn-warning">
                            Download
                        </a>

                        {% post_to_whatsapp object_or_url "Share via WhatsApp" %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        <!-- end of accordion -->
    </div>
</div>

{% endblock %}

{% block js %}
<script>
    var recording = false;
    var mediaRecorder;
    var chunks = [];
    var timer = null;
    var recordingTime = 0;

    function startRecording() {
        console.log(`START...`);

        navigator.mediaDevices.getUserMedia({ audio: true })
            .then(function (stream) {
                mediaRecorder = new MediaRecorder(stream);
                mediaRecorder.addEventListener("dataavailable", function (event) {
                    chunks.push(event.data);
                });
                mediaRecorder.addEventListener("stop", function () {
                    var blob = new Blob(chunks, { type: "audio/wav" });
                    clearInterval(timer);
                    recordingTime = 0;
                    var formData = new FormData();
                    formData.append("audio_blob", blob, "recording.wav");
                    formData.append("csrfmiddlewaretoken", '{{ csrf_token }}')
                    $.ajax({
                        url: "{% url 'main:upload' %}",
                        type: "POST",
                        data: formData,
                        processData: false,
                        contentType: false,
                        success: function () {
                            chunks = [];
                        }
                    });
                });
                mediaRecorder.start();
                recording = true;
                startTimer();
            });
    }

    function stopRecording() {
        console.log(`STOP!`);
        mediaRecorder.stop();
        clearInterval(timer);
        recordingTime = 0;
        recording = false;
    }

    function startTimer() {
        timer = setInterval(function () {
            recordingTime++;
            document.getElementById("recording-time").innerText = "Recording time: " + recordingTime + " seconds";
        }, 1000);
    }

    document.getElementById("record-button").addEventListener("click", function () {
        if (recording) {
            stopRecording();
            document.getElementById("record-button").innerText = "Record";
            document.getElementById("recording-time").innerText = "";
        } else {
            console.log(`starting record...`);
            startRecording();
            document.getElementById("record-button").innerText = "Stop";
        }
    });
</script>
{% endblock js %}